version: "3"
services:
  agent:
    image: docker.elastic.co/beats/elastic-agent:${ELK_VERSION:-8.8.2}
    container_name: agent
    #restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_ENROLLMENT_TOKEN=${ENROLLMENT_TOKEN}
      - FLEET_ENROLL=1
      - FLEET_URL=https://kibana:5601