version: "3.8"
services:
  agent:
    image: docker.elastic.co/beats/elastic-agent:${ELK_VERSION:-8.8.2}
    container_name: agent
    volumes:
      - certs:/usr/share/elastic-agent/certs
    networks:
      - elastic_net      
    #restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - ELASTIC_AGENT_TAGS=Agent-1
      - FLEET_ENROLLMENT_TOKEN=${AGENT_ENROLLMENT_TOKEN}
      - FLEET_TOKEN_POLICY_NAME=${AGENT_POLICY_ID}
      - FLEET_ENROLL=true
      - FLEET_URL=https://fleet-svr:8220
      - FLEET_CA=/usr/share/elastic-agent/certs/ca.crt

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ./certs      

networks:
  elastic_net:
    external: true      