version: "3.8"

services:
  es-a1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: es-a1
    hostname: es-a1
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_a1_data:/usr/share/elasticsearch/data
      - es_a1_logs:/usr/share/elasticsearch/logs
      - snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - elastic_net
    ports:
      - 9200:9200
    environment:
      - node.name=es-a1
      - cluster.name=${ES_CLUSTER:-elk-cluster}
      - cluster.initial_master_nodes=es-a1,es-a2,es-a3
      - discovery.seed_hosts=es-a2,es-a3
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-password}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.monitoring.collection.enabled=true 
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - path.repo=/usr/share/elasticsearch/snapshots
      - node.attr.node_type=hot
    #mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s  http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-a2:
    depends_on:
      - es-a1
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: es-a2
    hostname: es-a2
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_a2_data:/usr/share/elasticsearch/data
      - es_a2_logs:/usr/share/elasticsearch/logs
      - snapshots:/usr/share/elasticsearch/snapshots      
    networks:
      - elastic_net
    environment:
      - node.name=es-a2
      - cluster.name=${ES_CLUSTER:-elk-cluster}
      - cluster.initial_master_nodes=es-a1,es-a2,es-a3
      - discovery.seed_hosts=es-a1,es-a3
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.monitoring.collection.enabled=true
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - path.repo=/usr/share/elasticsearch/snapshots
      - node.attr.node_type=warm
    #mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s  http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-a3:
    depends_on:
      - es-a2
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: es-a3
    hostname: es-a3
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_a3_data:/usr/share/elasticsearch/data
      - es_a3_logs:/usr/share/elasticsearch/logs
      - snapshots:/usr/share/elasticsearch/snapshots      
    networks:
      - elastic_net
    environment:
      - node.name=es-a3
      - cluster.name=${ES_CLUSTER:-elk-cluster}
      - cluster.initial_master_nodes=es-a1,es-a2,es-a3
      - discovery.seed_hosts=es-a1,es-a2
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.monitoring.collection.enabled=true
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - path.repo=/usr/share/elasticsearch/snapshots   
      - node.attr.node_type=warm
    #mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
         [
          "CMD-SHELL",
          "curl -s  http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      - es-a1
      - es-a2
      - es-a3
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION:-8.8.2}
    container_name: kibana
    hostname: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    networks:
      - elastic_net
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es-a1:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME:-kibana_system}
      - xpack.security.cookieName=${ES_CLUSTER:-elk-cluster}_5601
      #- ELASTICSEARCH_USERNAME=elastic # for older version of ELK
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-password}
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
    #mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s  http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/config/certs
  es_a1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a1/data
  es_a1_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a1/logs
  es_a2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a2/data
  es_a2_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a2/logs
  es_a3_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a3/data
  es_a3_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a3/logs
  kibanadata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/kibana/data
  snapshots:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/snapshots

networks:
  elastic_net:
    external: true
