version: "3.8"


services:
  apm-svr:
    image: docker.elastic.co/apm/apm-server:${ELK_VERSION:-8.8.2}
    container_name: apm-svr 
    ports:
      - 8200:8200
    volumes:
      - ${PWD}/apm-server.yml:/usr/share/apm-server/apm-server.yml
      - certs:/usr/share/apm-server/certs
    networks:
      - elastic_net
    mem_limit: 1g
      
volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ./certs

networks:
  elastic_net:
    external: true