version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    networks:
      - spark-network

  spark-worker1:
    image: bitnami/spark:latest
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  spark-worker2:
    image: bitnami/spark:latest
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  spark-worker3:
    image: bitnami/spark:latest
    container_name: spark-worker3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  jupyterlab:
    image: jupyter/pyspark-notebook
    container_name: jupyterlab
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    environment:
      - NB_UID=1000
      - NB_GID=1000
      - SPARK_HOME=/usr/local/spark
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_OPTS=--driver-memory=2g --executor-memory=1g
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - spark-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - spark-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - spark-network


networks:
  spark-network:
