version: "3.8"


services:
  apm-svr:
    #image: docker.elastic.co/apm/apm-server:${ELK_VERSION:-8.10.2}
    image: apm-svr:${ELK_VERSION}
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: apm-svr 
    ports:
      - 8200:8200
    volumes:
      - ${PWD}/apm-server.yml:/usr/share/apm-server/apm-server.yml
      - certs:/usr/share/apm-server/certs
    networks:
      - elastic_net
    mem_limit: 1g
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -i http://apm-svr:8200  | grep -q 'HTTP/1.1 200 OK'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
      
volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certs

networks:
  elastic_net:
    external: true