filebeat.inputs:
- type: syslog
  protocol.udp:
    host: "0.0.0.0:514"

output.elasticsearch:
  hosts: ["https://es-a1:9200"]  # HTTPS URL
  protocol: "https"
  username: "elastic"  # Optional, remove if not using authentication
  password: "password"  # Optional, remove if not using authentication
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca.crt"]  # Path to CA cert in container
  ssl.verification_mode: none

setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "kibana:5601"

  # Optional protocol and basic auth credentials.
  protocol: "https"
  username: "elastic"
  password: "password"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca.crt"]  # Path to CA cert in container
  ssl.verification_mode: none  