version: "3.8"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: setup 
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    networks:
      - data-network
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD:-password} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD:-password} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
        fi;
        unzip config/certs/ca.zip -d config/certs;

        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es-a1\n"\
          "    dns:\n"\
          "      - es-a1\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-a2\n"\
          "    dns:\n"\
          "      - es-a2\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-a3\n"\
          "    dns:\n"\
          "      - es-a3\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: fleet-svr\n"\
          "    dns:\n"\
          "      - fleet-svr\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;


        echo "Setting file permissions ...";
        chown -R root:root config/certs;
        
        find . -type d -exec chmod 777 \{\} \;;
        find . -type f -exec chmod 666 \{\} \;;
        
        echo "Waiting for Elasticsearch availability ...";
        until curl -s -X GET --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD:-password}" -H "Content-Type: application/json" https://es-a1:9200 | grep -q "You Know, for Search"; do sleep 10; done;

        echo "Setting kibana_system password ...";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD:-password}" -H "Content-Type: application/json" https://es-a1:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD:-password}\"}" | grep -q "^{}"; do sleep 5; done;

        echo "Setting Trial licence...";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD:-password}" -H "Content-Type: application/json" https://es-a1:9200/_license/start_trial?acknowledge=true  | grep -q "trial_was_started"; do sleep 5; done;

        #echo "Setting Kibana dark mode...";
        #until curl -s -X PUT  -u "elastic:${KIBANA_PASSWORD:-password}" -H "kbn-xsrf: true" -H "Content-Type: application/json" https://kibana:5601/api/saved_objects/config/"${ELK_VERSION:-8.8.2}"   -d "{\"attributes\":  { \"theme:darkMode\" : true} }" | grep -q "updated_at"; do sleep 5; done;

        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es-a1/es-a1.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  es-a1:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: es-a1
    hostname: es-a1
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_a1_data:/usr/share/elasticsearch/data
      - es_a1_logs:/usr/share/elasticsearch/logs
      - snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - data-network
    ports:
      - 9200:9200
    environment:
      - node.name=es-a1
      - cluster.name=${ES_CLUSTER:-elk-cluster}
      - cluster.initial_master_nodes=es-a1,es-a2,es-a3
      - discovery.seed_hosts=es-a2,es-a3
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-a1/es-a1.key
      - xpack.security.http.ssl.certificate=certs/es-a1/es-a1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-a1/es-a1.key
      - xpack.security.transport.ssl.certificate=certs/es-a1/es-a1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.monitoring.collection.enabled=true 
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-password}
      - path.repo=/usr/share/elasticsearch/snapshots
      - node.attr.node_type=hot
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}  --cacert config/certs/ca/ca.crt https://es-a1:9200 | grep -q 'You Know, for Search'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-a2:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: es-a2
    hostname: es-a2
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_a2_data:/usr/share/elasticsearch/data
      - es_a2_logs:/usr/share/elasticsearch/logs
      - snapshots:/usr/share/elasticsearch/snapshots      
    networks:
      - data-network
    ports:
      - 9201:9200      
    environment:
      - node.name=es-a2
      - cluster.name=${ES_CLUSTER:-elk-cluster}
      - cluster.initial_master_nodes=es-a1,es-a2,es-a3
      - discovery.seed_hosts=es-a1,es-a3
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-a2/es-a2.key
      - xpack.security.http.ssl.certificate=certs/es-a2/es-a2.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-a2/es-a2.key
      - xpack.security.transport.ssl.certificate=certs/es-a2/es-a2.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.monitoring.collection.enabled=true
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-password}
      - path.repo=/usr/share/elasticsearch/snapshots
      - node.attr.node_type=warm
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}  --cacert config/certs/ca/ca.crt https://es-a2:9200 | grep -q 'You Know, for Search'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-a3:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.8.2}
    container_name: es-a3
    hostname: es-a3
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_a3_data:/usr/share/elasticsearch/data
      - es_a3_logs:/usr/share/elasticsearch/logs
      - snapshots:/usr/share/elasticsearch/snapshots      
    networks:
      - data-network
    ports:
      - 9202:9200      
    environment:
      - node.name=es-a3
      - cluster.name=${ES_CLUSTER:-elk-cluster}
      - cluster.initial_master_nodes=es-a1,es-a2,es-a3
      - discovery.seed_hosts=es-a1,es-a2
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-a3/es-a3.key
      - xpack.security.http.ssl.certificate=certs/es-a3/es-a3.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-a3/es-a3.key
      - xpack.security.transport.ssl.certificate=certs/es-a3/es-a3.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.monitoring.collection.enabled=true
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-password}
      - path.repo=/usr/share/elasticsearch/snapshots   
      - node.attr.node_type=warm
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}  --cacert config/certs/ca/ca.crt https://es-a3:9200 | grep -q 'You Know, for Search'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      es-a1:
        condition: service_healthy
      es-a2:
        condition: service_healthy
      es-a3:
        condition: service_healthy   
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION:-8.8.2}
    container_name: kibana
    hostname: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    networks:
      - data-network
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es-a1:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME:-kibana_system}
      - xpack.security.cookieName=${ES_CLUSTER:-elk-cluster}_5601
      #- ELASTICSEARCH_USERNAME=elastic # for older version of ELK
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-password}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=config/certs/kibana/kibana.crt
      - SERVER_SSL_KEY=config/certs/kibana/kibana.key
      - SERVER_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt      
      - 'ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}'
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://kibana:5601/login | grep -q '<title>Elastic</title>'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/config/certs
  es_a1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a1/data
  es_a1_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a1/logs
  es_a2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a2/data
  es_a2_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a2/logs
  es_a3_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a3/data
  es_a3_logs:
    driver: local
    driver_opts:
      type: none
      o: bindfile:///home/user1/apps/data_engineering/elastic/docker_build/elk/a/start.sh

      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/es-a3/logs
  kibanadata:
    driver: local
    driver_opts:
      type: none
      o: bindfile:///home/user1/apps/data_engineering/elastic/docker_build/elk/a/build_elk.sh

      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/kibana/data
  snapshots:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  ${ES_FOLDER}/${ES_CLUSTER:-elk-cluster}/snapshots

networks:
  data-network:
    external: true
